Update script

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -116,17 +116,20 @@ jobs:
         run: |
           # Send command and capture ID
           COMMAND_ID=$(aws ssm send-command \
-          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
-          --document-name "AWS-RunShellScript" \
-          --parameters '{
-            "commands":[
-              "export HOME=/home/ubuntu",
-              "git config --global --add safe.directory /home/ubuntu/budget-app-eliorabaev",
-              "cd /home/ubuntu/budget-app-eliorabaev && git pull && chmod +x ./deploy-from-ecr.sh && ./deploy-from-ecr.sh && docker ps"
-            ]
-          }' \
-          --run-as-user "ubuntu" \
-          --output json | jq -r '.Command.CommandId')
+            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
+            --document-name "AWS-RunShellScript" \
+            --parameters '{
+              "commands":[
+                "sudo -H -u ubuntu bash -c \"export HOME=/home/ubuntu && cd /home/ubuntu/budget-app-eliorabaev && git pull && chmod +x ./deploy-from-ecr.sh && ./deploy-from-ecr.sh && docker ps\""
+              ]
+            }' \
+            --output json | jq -r '.Command.CommandId')
+          
+          # Check if COMMAND_ID is empty (for better error handling)
+          if [ -z "$COMMAND_ID" ]; then
+            echo "Failed to get Command ID from send-command operation."
+            exit 1
+          fi
           
           echo "Started deployment with command ID: $COMMAND_ID"
           
@@ -160,9 +163,12 @@ jobs:
               --query "StandardOutputContent" --output text
           else
             echo "Deployment failed with status: $STATUS. Error output:"
-            aws ssm get-command-invocation \
-              --command-id "$COMMAND_ID" \
-              --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
-              --query "StandardErrorContent" --output text
+            # Avoid running get-command-invocation again if the initial command failed
+            if [ "$STATUS" != "Failed to get status" ]; then
+              aws ssm get-command-invocation \
+                --command-id "$COMMAND_ID" \
+                --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
+                --query "StandardErrorContent" --output text
+            fi
             exit 1
           fi
